FROM ubuntu:latest
USER root
RUN apt-get install -y curl
RUN apk add curl
COPY . /app
ADD https://example.com/file.tar.gz /tmp
ENV PASSWORD=secret123
HEALTHCHECK NONE
read-only
RUN apt-get install -y openssh-server
